// Barrel re-export — all public API surfaces from the split modules.
// Consumers should gradually migrate to importing from the specific module.

export {
  CANONICAL_TOKENS,
  PATTERN_WEIGHT,
  VOWEL_LABELS,
  RHYME_ALIASES,
  PATTERN_GROUP_REGEX,
  CLICHE_FRAGMENTS,
  SEED_ENTRY_SPECS,
  PREPOSITIONS,
  ARTICLES,
  CONJUNCTIONS,
  PRONOUNS,
  AUXILIARIES,
  COMMON_VERBS,
  COMMON_ADJECTIVES,
  LYRIC_PATTERN_OVERRIDES,
  THEME_ALIASES,
  FOUR_GROUP_TEMPLATES,
  TEMPLATE_BONUS,
} from "./stressConstants.js";

export {
  normalizeWordKey,
  normalizeText,
  PRONUNCIATION_MAP,
  extractStressToken,
  buildPattern,
  deriveCompactPattern,
  deriveRhymeInfo,
} from "./pronunciation.js";

export {
  parsePatternDetailed,
  parsePattern,
  matchesPattern,
  compactRelaxationPatterns,
  lyricSliceVariants,
  patternsCompatible,
} from "./patternParser.js";

export {
  SEED_SPEC_MAP,
  LEXICON,
  LEXICON_BY_WORD,
  LYRIC_LEXICON_BY_PATTERN,
  LYRIC_LEXICON_BY_COMPACT_PATTERN,
  RAW_LEXICON_BY_PATTERN,
  RAW_LEXICON_BY_COMPACT_PATTERN,
  FAMILIAR_PROMPT_WORDS,
  resolveLexiconEntry,
  lexicalVariants,
  deriveProgressiveForms,
  filterUsableSeedWords,
  filterUsableSeedPool,
  normalizeRhymeTarget,
  resolveRhymeTarget,
  coverageBand,
  coverageExamples,
  shapeCoverageForSlot,
  lyricEntriesForPattern,
  familiarEntryCountForSlice,
  familiarCoverageScoreForSlot,
  planRealizabilityScore,
  slotPosCoverageCount,
  getLexiconSnapshot,
  getLyricShapeCoverageSnapshot,
  getThemeAliasSnapshot,
} from "./lexicon.js";

export { parseThemeTags, analyzeIdeaCoverage } from "./theme.js";

export { validateLine, matchesSegmentationPlan } from "./validation.js";

export {
  lyricPatternPenalty,
  slotTypePenalty,
  slotMatches,
  slotMatchPenalty,
  sliceWeight,
  rhymeScore,
  themeScore,
  densityPenalty,
  detectCliches,
  rhymeMaster,
  tasteGuardian,
  clicheChecker,
  storyWeaver,
  chooseDefaultRhyme,
  lineToText,
  hasWeakEnding,
  hasFunctionWordPile,
  hasBasicSyntaxGap,
  hasAwkwardVerbChain,
  hasRepeatedWordEntries,
  hasTooManyColdWords,
  lineIdeaScore,
  lineFamiliarityScore,
  planStructureScore,
  scoreCandidate,
  lexicalOverlapScore,
  contentWordsForLine,
  contentOverlapScore,
  sameContentSet,
  frameSignature,
  anchorSignature,
  singleEntryFamiliarityScore,
  strictSlotKindMatch,
  promptSlotCompatibility,
  promptContextScore,
} from "./scoring.js";

export {
  deriveSlotKindForPlanSlot,
  segmentationPlanKey,
  enumerateSegmentationPlans,
  buildGenerationTemplates,
  slotPlanKey,
  chooseCandidatesForSlot,
  promptExamplesForSlot,
  promptCandidateBankForSlot,
  filterPlanSegmentCandidates,
  explainSlotPlanning,
  summarizeSlotPlanNeeds,
  summarizeModePlans,
  selectPlanRepresentatives,
  planKindsFromKey,
  planFrameSignature,
  planStartKind,
  planShapesFromKey,
  classifyPlanLengthMode,
  planNaturalnessScore,
} from "./slotPlanning.js";

export {
  generateLyrics,
  evaluateCandidateLine,
  realizeSegmentationPlan,
  debugComposeFallback,
  debugStructuredHybridCandidates,
  debugSlotCandidates,
  debugPlanAssembly,
  explainCandidateDebug,
} from "./generation.js";
