// Vercel silently strips node_modules from the deploy bundle even with
// .vercelignore claiming to keep it. So instead of importing the CMU
// pronouncing-dictionary npm package, we fetch a pre-built static JSON
// at module load (top-level await). Generated by scripts/buildCmuDict.mjs.
import { VOWEL_LABELS } from "./stressConstants.js";

export function normalizeWordKey(word) {
  return word.toLowerCase();
}

export function normalizeText(text) {
  return text
    .toLowerCase()
    .replaceAll(/[^a-z0-9'\s]/gu, " ")
    .split(/\s+/u)
    .filter(Boolean);
}

async function loadCmuDictionary() {
  const url = new URL("../wordlists/cmu-dict.json", import.meta.url);
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to load CMU dict (${response.status}) — expected at ${url}`);
  }
  return response.json();
}

async function loadOverrides() {
  // Hand-curated patches over CMU 0.7b mis-transcriptions (e.g. typology).
  // Verified against Wiktionary US IPA. Optional file — silently skip on 404.
  const url = new URL("../wordlists/cmu-overrides.json", import.meta.url);
  try {
    const response = await fetch(url);
    if (!response.ok) return {};
    const obj = await response.json();
    const cleaned = {};
    for (const word in obj) {
      if (word.startsWith("_")) continue;
      cleaned[word.toLowerCase()] = obj[word];
    }
    return cleaned;
  } catch {
    return {};
  }
}

async function buildPronunciationMap() {
  const [cmuDictionary, overrides] = await Promise.all([
    loadCmuDictionary(),
    loadOverrides(),
  ]);
  const pronunciationMap = new Map();
  for (const rawWord in cmuDictionary) {
    const normalizedWord = rawWord.toLowerCase().replace(/\(\d+\)$/u, "");
    if (!pronunciationMap.has(normalizedWord)) {
      pronunciationMap.set(normalizedWord, cmuDictionary[rawWord].split(" "));
    }
  }
  // Apply overrides last so they win against the base CMU entry.
  for (const word in overrides) {
    pronunciationMap.set(word, overrides[word].split(" "));
  }
  return pronunciationMap;
}

export const PRONUNCIATION_MAP = await buildPronunciationMap();

export function extractStressToken(phoneme) {
  const match = phoneme.match(/([A-Z]{2})([012])/u);
  if (!match) {
    return null;
  }

  const [, vowel, stress] = match;
  return {
    vowel,
    stressToken: stress === "1" ? "DUM" : stress === "2" ? "dum" : "da",
  };
}

export function buildPattern(phonemes) {
  return phonemes.map(extractStressToken).filter(Boolean).map((item) => item.stressToken);
}

export function deriveCompactPattern(pattern) {
  return pattern.join("");
}

export function deriveRhymeInfo(phonemes) {
  let lastStressedIndex = -1;

  for (let index = 0; index < phonemes.length; index += 1) {
    if (/[12]/u.test(phonemes[index])) {
      lastStressedIndex = index;
    }
  }

  if (lastStressedIndex === -1) {
    lastStressedIndex = phonemes.findIndex((phoneme) => /\d/u.test(phoneme));
  }

  const tail = lastStressedIndex === -1 ? phonemes : phonemes.slice(lastStressedIndex);
  const vowel = extractStressToken(tail[0] ?? "");

  return {
    rhymeTail: tail,
    rhymeKey: tail.join(" "),
    rhymeVowel: vowel ? VOWEL_LABELS[vowel.vowel] ?? vowel.vowel.toLowerCase() : "",
  };
}
